# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: ./server
    schedule:
      interval: daily
    assignees: [lildeadprince]

  - package-ecosystem: npm
    directory: ./client
    schedule:
      interval: daily
    assignees: [lildeadprince]
