# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

env:
  GAR_BASE: ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GCP login
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GAR_JSON_KEY }}

      - name: Deploy latest at GCR
        id: gcr_deploy
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: ${{ secrets.GCP_PROJECT_ID }}
          image: ${{ env.GAR_BASE }}/${{ secrets.GAR_REGISTRY_NAME }}/auth-me-server:latest
