# This is a basic workflow to help you get started with Actions

name: Deploy to Cloud Run

on:
  workflow_call:
    inputs:
      imageName:
      service:
        type: string
        required: true
      region:
        type: string
        required: true
      suffix:
        type: string
    secrets:
      GCP_PROJECT_ID:
        type: string
        required: true
      GAR_REGISTRY_NAME:
        type: string
        required: true


  workflow_dispatch:
    inputs:
      imageName:
        description: 'Name of an image to deploy'
        type: string
      service:
        description: 'Service ID'
        required: true
      region:
        type: choice
        description: 'Target deployment region'
        default: 'europe-west1'
        options:
          - europe-west1
          - europe-north1
        required: true
      suffix:
        description: 'Deployment name suffix'
        default: 'server-eu-west'

env:
  service: ${{ inputs.service || github.event.inputs.service }}
  suffix: ${{ inputs.suffix || github.event.inputs.suffix }}
  region: ${{ inputs.region || github.event.inputs.region }}
  imageName: ${{ inputs.imageName || github.event.inputs.imageName }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GCP login
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GAR_JSON_KEY }}

      - name: Deploy latest at GCR
        id: gcr_deploy
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: ${{ env.service }}
          suffix: ${{ env.suffix }}
          region: ${{ env.region }}
          image: {{ env.region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REGISTRY_NAME }}/${{ env.imageName }}

      - name: Expose deployment URL
        run: echo '::set-output name=deployment_url::${{ steps.gcr_deploy.outputs.url }}'
