name: Build & Push server image to GAR

on:
  push:
    branches: [ master, dev ]
    paths: [server/**]

  workflow_dispatch:

env:
  registry: ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}
  imageName: ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REGISTRY_NAME }}/auth-me-server:latest

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GAR
        id: docker_login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push to GAR
        id: docker_build_and_push
        uses: docker/build-push-action@v2
        with:
          context: ./server
          tags: ${{ env.imageName }}
          push: true
          cache-from: type=registry,ref=${{ env.imageName }}
          cache-to: type=inline

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: success() && github.ref == 'refs/heads/master'

    steps:
      - name: GCP login
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GAR_JSON_KEY }}

      - name: Deploy latest at GCR
        id: gcr_deploy
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: auth-me-server-eu-west
          region: ${{ secrets.GAR_REGION }}
          image: ${{ env.imageName }}

      - name: Expose deployment URL
        run: echo '::set-output name=deployment_url::${{ steps.gcr_deploy.outputs.url }}'
