# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          target: release
          tags: ${{ env.GAR_BASE }}/${{env.PROJECT_NAME}}/auth-me-server:latest
          build-args: |
            NODE_ENV=${{ env.NODE_ENV }}
            REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
            SKIP_PREFLIGHT_CHECK=${{ env.SKIP_PREFLIGHT_CHECK }}
            DISABLE_ESLINT_PLUGIN=${{ env.DISABLE_ESLINT_PLUGIN }}
          push: true
          cache-from: type=registry,ref=${{ env.GAR_BASE }}/auth-me-server:latest
          cache-to: type=inline
